# Generated by Django 5.2 on 2025-04-26 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_personalized',
            field=models.BooleanField(default=False, help_text='Whether this conversation uses personalized preferences'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('general', 'General Message'), ('question', 'Preference Question'), ('answer', 'Preference Answer'), ('recommendation', 'Remedy Recommendation')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='preference_key',
            field=models.CharField(blank=True, help_text='For preference questions/answers, the key being asked about', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='For non-logged in users', max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_35', '18-35'), ('36_50', '36-50'), ('51_plus', '51+')], max_length=20, null=True)),
                ('wellness_goal', models.CharField(blank=True, choices=[('stress_relief', 'Stress Relief'), ('better_sleep', 'Better Sleep'), ('digestive_health', 'Digestive Health'), ('pain_relief', 'Pain Relief'), ('other', 'Other')], max_length=20, null=True)),
                ('allergies', models.CharField(blank=True, choices=[('none', 'None'), ('pollen', 'Pollen'), ('nuts', 'Nuts'), ('other', 'Other')], max_length=20, null=True)),
                ('other_allergies', models.TextField(blank=True, help_text="If 'Other' is selected for allergies")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='preferences',
            field=models.ForeignKey(blank=True, help_text='User preferences for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='Core.userpreferences'),
        ),
    ]
